{%- set hasSubscribe = false -%}
{%- set hasPublish = false -%}
{%- for channelName, channel in asyncapi.channels() -%}
    {%- if channel.hasPublish() -%}
        {%- set hasPublish = true -%}
    {%- endif -%}
    {%- if channel.hasSubscribe() -%}
        {%- set hasSubscribe = true -%}
    {%- endif -%}
{%- endfor -%}
{%- if asyncapi | isProtocol('amqp') %}
amqp:
  broker:
    host: localhost
    port: 5672
    username: guest
    password: guest
  exchange:
  {% for channelName, channel in asyncapi.channels() %}
    {% if channel.hasSubscribe() and channel.subscribe().bindings('amqp') %}
    {{channel.subscribe().bindings('amqp').exchange().name()}}: {{channelName}}
    {% endif %}
  {% endfor %}
  queue:
  {% for channelName, channel in asyncapi.channels() %}
    {% if channel.hasPublish() and channel.publish().bindings('amqp') %}
    {{channel.publish().bindings('amqp').queue().name()}}: {{channelName}}
    {% endif %}
  {% endfor %}
{% endif %}
{%- if asyncapi | isProtocol('mqtt') %}
  {% for serverName, server in asyncapi.servers() %}
mqtt:
  broker:
    host: tcp://{{server.url()}}
    port: {{server.variables(port).defaultValue()}}
    username:
    password:
  topic:
    {% for channelName, channel in asyncapi.channels() %}
    {{channelName}}Topic: {{channelName}}
    {% endfor %}
  {% endfor %}
{% endif %}
{%- if asyncapi | isProtocol('kafka') %}
spring:
  kafka:
    bootstrap-servers: {% for serverName, server in asyncapi.servers() %}{% if server.variable('port') %}{{server.url() | replace('{port}', server.variable('port').defaultValue())}}{% else %}{{server.url()}}{% endif %}{% if not loop.last %},{% endif %}{% endfor %}
  {%- if hasPublish %}
    listener:
      poll-timeout: {% if params.listenerPollTimeout %}{{params.listenerPollTimeout}}{% else %}3000{% endif%}
      concurrency: {% if params.listenerConcurrency %}{{params.listenerConcurrency}}{% else %}3{% endif%}
  {% endif %}
{% endif %}