{%- set hasSubscribe = false -%}
{%- set hasPublish = false -%}
{%- for channelName, channel in asyncapi.channels() -%}
    {%- if channel.hasPublish() -%}
        {%- set hasPublish = true -%}
    {%- endif -%}
    {%- if channel.hasSubscribe() -%}
        {%- set hasSubscribe = true -%}
    {%- endif -%}
{%- endfor -%}
{%- for serverName, server in asyncapi.servers() %}{% if server.protocol() == 'amqp' %}
amqp:
  broker:
    host: {{server.url() | replace(':{port}', '') }}
    port: {% if server.variable('port') %}{{server.variable('port').defaultValue()}}{% endif %}
    username:
    password:
  exchange:
  {% for channelName, channel in asyncapi.channels() %}
    {% if channel.hasSubscribe() and channel.subscribe().binding('amqp') %}
    {{channelName}}: {{channel.subscribe().binding('amqp').exchange.name}}
    {% endif %}
  {% endfor %}
  queue:
  {% for channelName, channel in asyncapi.channels() %}
    {% if channel.hasPublish() and channel.publish().binding('amqp') %}
    {{channelName}}: {{channel.publish().binding('amqp').queue.name}}
    {% endif %}
  {% endfor %}
{% endif %}
{% if server.protocol() == 'mqtt' %}
mqtt:
  broker:
    host: tcp://{{server.url() | replace(':{port}', '')}}
    port: {% if server.variable('port') %}{{server.variable('port').defaultValue()}}{% endif %}
    username:
    password:
  topic:
    {% for channelName, channel in asyncapi.channels() %}
    {{channelName}}Topic: {{channelName}}
    {% endfor %}
{% endif %}{% endfor %}
{%- if asyncapi | isProtocol('kafka') %}
kafka:
  bootstrap-servers: {% for serverName, server in asyncapi.servers() %}{% if server.variable('port') %}{{server.url() | replace('{port}', server.variable('port').defaultValue())}}{% else %}{{server.url()}}{% endif %}{% if not loop.last %},{% endif %}{% endfor %}
  {%- if hasPublish %}
  subscribe:
    pool-timeout: 3000
    amount-of-listeners: 3
  {% endif %}
{% endif %}