{%- set hasSubscribe = false -%}
{%- set hasPublish = false -%}
{%- for channelName, channel in asyncapi.channels() -%}
    {%- if channel.hasPublish() -%}
        {%- set hasPublish = true -%}
    {%- endif -%}
    {%- if channel.hasSubscribe() -%}
        {%- set hasSubscribe = true -%}
    {%- endif -%}
{%- endfor -%}
{%- for serverName, server in asyncapi.servers() %}{% if server.protocol() == 'amqp' %}
amqp:
  broker: {% for line in server.description() | splitByLines %}
    # {{line | safe}}{% endfor %}
    host: localhost
    port: 5672
    username: guest
    password: guest
  exchange:
  {% for channelName, channel in asyncapi.channels() %}
    {% if channel.hasSubscribe() and channel.subscribe().bindings('amqp') %}
    {{channel.subscribe().bindings('amqp').exchange().name()}}: {{channelName}}
    {% endif %}
  {% endfor %}
  queue:
  {% for channelName, channel in asyncapi.channels() %}
    {% if channel.hasPublish() and channel.publish().bindings('amqp') %}
    {{channel.publish().bindings('amqp').queue().name()}}: {{channelName}}
    {% endif %}
  {% endfor %}
{% endif %}
{% if server.protocol() == 'mqtt' %}
mqtt:
  broker: {% for line in server.description() | splitByLines %}
    # {{line | safe}}{% endfor %}
    host: tcp://{{server.url()}}
    port: {{server.variables(port).defaultValue()}}
    username:
    password:
  topic:
    {% for channelName, channel in asyncapi.channels() %}
    {{channelName}}Topic: {{channelName}}
    {% endfor %}
{% endif %}{% endfor %}
{%- if asyncapi | isProtocol('kafka') %}
kafka: {% for serverName, server in asyncapi.servers() %}
  # - {{serverName}} in {{server.url()}} : {% for line in server.description() | splitByLines %}
  # {{line | safe}}{% endfor %}{% endfor %}
  bootstrap-servers: {% for serverName, server in asyncapi.servers() %}{{server.url()}}{% if not loop.last %},{% endif %}{% endfor %}
  {%- if hasPublish %}
  subscribe:
    pool-timeout: 3000
    amount-of-listeners: 3
  {% endif %}
{% endif %}